### PR TITLE
claim-bot interaction fixed

### LINKED ISSUE #246: Disable buttons when clicked.
I've ran through the whole simulation of claiming a cryptobot with two people so far. 
Both of them ended up clicking the button to confirm, twice - which opens up two confirm modals. 
This is because Temple is slow in responding with the pop-up which asks them to sign the transaction. 
Disabling the button when clicked, should prevent this behavior.

### PR DESCRIPTION
**Pull request by manangouhari**
Closes #246 

### How to manually test?
1. Go to `/tezos/customizebot`
2. Click on "Claim Bot." It'll take you to `/claim-transaction` page.
3. On the `/claim-transaction` page, click on "Confirm."

### CODE REVIEW

**Comment by manangouhari** [comment]
> In case the balance is empty or insufficient. It will show the loading. Confirm if this UX makes sense or not.

No, that is not the intended interaction. Will fix it.

**Comment by bhaskarSingh** [comment]
>In case the balance is empty or insufficient. It will show the loading. Confirm if this UX makes sense or not.

Demo link: https://www.loom.com/share/f0e7e36534934ca49b1039dac8d5f160

@harsh242  What UX will make sense here?

**Comment by harsh242** [comment]
>Demo link: https://www.loom.com/share/f0e7e36534934ca49b1039dac8d5f160

@harsh242 What UX will make sense here?


@bhaskarSingh 2nd one which is live on the develop one makes sense.
Loading interaction just confuses the user that there's still something left to load.

**Comment by manangouhari** [comment]
@bhaskarSingh please test this out. Should be good to go now.

File: src/pages/tezos/cryptobot/[id].js [hunk 1]
```diff
@@ -248,7 +248,11 @@ function BotView({ location }) {
             >
               {claimButtonDisabled ? (
                 <div className={`flex justify-center align-center`}>
-                  <Loader type="ThreeDots" color="#BFDBFE" height={28} />
+                  {getUserBalance.value > 0.5 ? (
+                    <Loader type="ThreeDots" color="#BFDBFE" height={28} />
+                  ) : (
+                    'Low Balance'
```
Comment (bhaskarSingh) [inline src/pages/tezos/cryptobot/[id].js:254]: Here I think rather than using `Low Balance` text, using `claim` makes sense since we are not showing an info here but it's an actual button with an action attached to it.

Comment (manangouhari) [reply src/pages/tezos/cryptobot/[id].js:254]: Yes, I agree. But labelling the button with the reason of why it's disabled felt more intuitive to me. 
I could be wrong here tho.

What do you think is optimal @harsh242 - Button text should be "Confirm" or "Low Balance" in case the button's disabled because the user doesn't have sufficient XTZ?

**Comment by bhaskarSingh** [comment]
@harsh242  ☝️

File: src/pages/tezos/cryptobot/[id].js (hunk 1 above)
Comment (bhaskarSingh) [reply src/pages/tezos/cryptobot/[id].js:254]: @harsh242  ☝️

Comment (harsh242) [reply src/pages/tezos/cryptobot/[id].js:254]: Keep the button text as "Confirm only", for low balance we were showing them the error right?

Comment (manangouhari) [reply src/pages/tezos/cryptobot/[id].js:254]: okay

**Comment by manangouhari** [comment]
@bhaskarSingh ready to be merged.

File: src/pages/tezos/claim-transaction.js [hunk 2]
```diff
@@ -409,17 +410,39 @@ function Transaction({ location }) {
...
-                  <Button
+                  <button
                     onClick={() => {
                       if (claimButtonDisabled) return;
+                      setClaimButtonDisabledStatus(true);
                       mintNFT();
                     }}
                     size="lg"
-                    type="primary"
+                    className={`${
```
Comment (bhaskarSingh) [inline src/pages/tezos/claim-transaction.js:420]: In case the balance is empty it's showing lighter blue color.
Screenshot 2021-03-24 at 1 56 04 PM

But, in the marketplace transaction view. It's showing darker blue color.
Screenshot 2021-03-24 at 1 55 23 PM

The discrepancy here needs to be fixed.

File: src/pages/tezos/cryptobot/[id].js [hunk 3]
```diff
@@ -403,10 +419,21 @@ function BotView({ location }) {
...
                 }
               }}
             >
-              Continue
+              {claimButtonDisabled ? (
+                <div className={`flex justify-center align-center`}>
+                  {getUserBalance.value > 0.5 ? (
+                    <Loader type="ThreeDots" color="#BFDBFE" height={28} />
+                  ) : (
+                    'Yes'
```
Comment (bhaskarSingh) [inline src/pages/tezos/cryptobot/[id].js:431]: Is there a state where `Yes` text might show up and if yes, what does it intends to indicate?

File: src/pages/tezos/cryptobot/[id].js [hunk 4]
```diff
@@ -782,8 +809,8 @@ const TransactionContainer = ({ children }) => {
 function ConfirmationModel(opHash) {
   return (
     <BaseModal>
-      <div className="grid grid-cols mx-auto justify-center mt-6 text-white mb-2">
-        <Loader type="BallTriangle" color="#2563EB" height={80} width={80} />
```
Comment (harsh242) [inline src/pages/tezos/cryptobot/[id].js:786]: Keep it Ball Triangle here just for consistency😅

File: src/pages/tezos/cryptobot/[id].js (hunk 3 above)
Comment (harsh242) [reply src/pages/tezos/cryptobot/[id].js:431]: This happens when we withdraw cryptobot from sale.
image

**Review by bhaskarSingh — APPROVED** [review]
